package com.mycompany.myapp.domain.enumeration;

/**
 * The Country enumeration.
 */
public enum Country {
    ANTARTICA, AMERICAN_SAMOA, AUSTRALIA, BELGIUM, BRAZIL, CANADA, SWITZERLAND, COOK_ISLANDS, CHINA, CUBA, GERMANY, DENMARK, SPAIN, FIJI_ISLANDS, FEDERATED_STATES_OF_MICRONESIA, FRANCE, GUAM, GREECE, HONG_KONG, INDONESIA, IRELAND, ISRAEL, INDIA, ITALY, JAMAICA, JAPAN, KENYA, KIRIBATI, NORTH_KOREA, SOUTH_KOREA, MARSHALL_ISLANDS, NORTHERN_MARIANA_ISLANDS, MALTA, MAURITIUS, MALDIVES, MALAYSIA, NEW_CALEDONIA, NORFOLK_ISLANDS, NETHERLANDS, NORWAY, NAURU, NIUE, NEW_ZEALAND, FRENCH_POLYNESIA, PAPUA_NEWGUINEA, PHILIPPINES, PACIFIC_REGION, PUERTO_RICO, PALAU, ALL_SOPAC_MEMBER_COUNTRIES, RUSSIAN_FEDERATION, SOLOMON_ISLANDS, SEYCHELLES, SWEDEN, SINGAPORE, USSR, THAILAND, TOKELAU, TONGA, TRINIDAD_AND_TOBAGO, TUVALU, TAIWAN, UNITED_KINGDOM, UNITED_STATES_OF_AMERICA, VANUATU, WALLIS_AND_FUTUNA, WORLD, SAMOA, SOUTH_AFRICA
}
