package com.mycompany.myapp.domain.enumeration;

/**
 * The Specialgeneral enumeration.
 */
public enum Specialgeneral {
    ADMINISTRATION, AGRICULTURE, ARCHITECTURE, BROADCASTING_OR_MEDIA, COMMUNICATIONS, COMMUNITY_DEVELOPMENT, DEFENSE, DISASTER_MANAGEMENT, ECONOMICS, EDUCATION_AND_TRAINING_AND_PUBLIC_AWARENESS, ELECTIRCIAN, FINANCE, FIRE_AND_SEARCH_AND_RESCUE, FIRST_AID_INSTRUCTOR, FOREIGN_AFFAIRS, HEALTH_EDUCATION, LAND_VALUATION, MANAGEMENT, MARITIME, MEDICAL_METEREOLOGICAL_SERVICES, MINERAL_RESOURCES, NATIONAL_PLANNING, POLICE, PRISON_SERVICES, PUBLIC_HEALTH, PUBLIC_WORK_AND_WATER, RED_CROSS, RESEARCH_DEPARTMENT, TRANSPORT
}
