export const enum SessionType {
  IN_COUNTRY_TECHNICAL_ASSISTANCE,
  INTERNATIONAL_COURSE,
  NATIONAL_COURSE,
  NATIONAL_SEMINAR_OR_WORKSHOP,
  POST_GRAD_CERTIFICATE_PROGRAMS,
  REGIONAL_COURSE,
  REGIONAL_SEMINAR_OR_WORKSHOP,
  SUB_NATIONAL_COURSE
}
